name: "Terraform Workflow"

on:
  workflow_dispatch:
    inputs:
      working_directory:
        description: "Caminho do diretório desejado para executar o Terraform"
        required: true
        type: string
  push:
    branches:
      - '**' 
  pull_request:
    branches:
      - '**'   

jobs:

  print:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Print Working Directory
        run: |
          echo "Working Directory: ${{ github.event.commits[0].message }}"
