name: "Terraform Workflow"

on:
  workflow_dispatch:
    inputs:
      working_directory:
        description: "Caminho do diretório desejado para executar o Terraform"
        required: true
        type: string
        default: "./modules/*"

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  configure-aws:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws-session-token: '${{ secrets.AWS_SESSION_TOKEN }}'
          aws-region: '${{ secrets.AWS_REGION }}'

  setup-terraform:
    runs-on: ubuntu-latest
    needs: configure-aws
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.3

  terraform-init:
    runs-on: ubuntu-latest
    needs: setup-terraform
    steps:
      - name: Terraform Init
        run: terraform init
        working-directory: ${{ github.event.inputs.working_directory }}

  terraform-validate:
    runs-on: ubuntu-latest
    needs: terraform-init
    steps:
      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ github.event.inputs.working_directory }}

  terraform-plan:
    runs-on: ubuntu-latest
    needs: terraform-validate
    steps:
      - name: Terraform Plan
        run: terraform plan
        working-directory: ${{ github.event.inputs.working_directory }}
        continue-on-error: true

  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform-plan
    if: ${{ github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ${{ github.event.inputs.working_directory }}